[project]
name = "enzyextract"
version = "0.0.1"
description = "EnzyExtract successor"
authors = [
  {name = "conjuncts"}
]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.9"

classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
]

dependencies = [
  "pandas",
  "polars",
  "litellm",
  "biopython",
  "seaborn",
  "anthropic",
  "gmft>=0.4.1",
  "ryaml",
  "tenacity",
  "colorama",
  "gmft_pymupdf @ git+https://github.com/conjuncts/gmft_pymupdf",
  "torchvision",
  "bs4",
  "transformers<5.4.0",
  "pyarrow",
  "rapidfuzz",
  "scipy",
]


[project.scripts]
enzyextract = "enzyextract.cli:main"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

